name: PR Style Bot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to run style checks on'
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write

jobs:
  debug-inputs:
      runs-on: ubuntu-latest
      steps:
        - name: Debug event context
          run: |
            echo "Event name: ${{ github.event_name }}"
            echo "PR number from event inputs: ${{ github.event.inputs.pr_number }}"
            echo "Raw event: ${{ toJSON(github.event) }}"
  style:
    uses: ./.github/workflows/bot-action.yml
    with:
      python_quality_dependencies: "[quality]"
      style_command_type: "default" 
      pr_number: ${{ fromJSON(github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number || github.event.issue.number) }}
    secrets:
      bot_token: ${{ secrets.GITHUB_TOKEN }}
