name: PR Style Bot

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to run style checks on'
        required: true
        type: string
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  style:
    uses: ./.github/workflows/bot-action.yml
    with:
      python_quality_dependencies: "[quality]"
      style_type: "default"
      pr_number: "${{ github.event.inputs.pr_number }}"
    secrets:
      bot_token: ${{ secrets.GITHUB_TOKEN }}
